#!/bin/sh

# cloneall
# Terminal script to execute 'git clone' on all my public GitHub repositories 
# to clone them into the current OS X directory

# to create:
# 1) in Terminal, cd to the folder containing this script 
# 2) type 'chmod +x cloneall' and hit Return to make file executable
# 3) copy this file to the folder where you want to clone my code

# to use: 
# 1) in Terminal, cd to the folder containing the copied script
# 2) type './cloneall' in Terminal and hit Return 
# all five repositories will be downloaded, ready for use

git clone https://github.com/SteveCaine/DebugUtil.git
git clone https://github.com/SteveCaine/DevUtil.git
git clone https://github.com/SteveCaine/FilesUtil.git
git clone https://github.com/SteveCaine/MapUtil.git
git clone https://github.com/SteveCaine/StringMapMaker.git
